/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import at.perses.io.FileInput;

import java.io.FileNotFoundException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        try {
            FileInput fi = new FileInput(App.class.getResource("test.txt").getPath());

            System.out.println(fi.readLine());

        } catch (java.io.IOException e) {
            e.printStackTrace();
        }

    }
}
