///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//
//import at.perses.contest.Image;
//import at.perses.io.FileInput;
//import at.perses.io.FileOutput;
//import org.apache.logging.log4j.LogManager;
//import org.apache.logging.log4j.Logger;
//import org.junit.After;
//import org.junit.Before;
//import org.junit.Test;
//
//import java.io.IOException;
//import java.util.ArrayList;
//import java.util.List;
//import java.util.stream.Collectors;
//
//public class Level1Test {
//    private static final Logger logger = LogManager.getLogger(Level1Test.class.getName());
//
//    private String inPath = "resources/level1/sample.inp";
//    private String outPath = "resources/level1/lvl1-0.out";
//
//    private FileInput input;
//    private FileOutput output;
//
//    @Before
//    public void setUp() throws IOException {
//        input = new FileInput(inPath);
//        output = new FileOutput(outPath);
//        logger.info("Setup done");
//    }
//
//    @After
//    public void tearDown() throws IOException {
//        logger.info("Tear down...");
//        output.close();
//        input.close();
//    }
//
//
//    @Test
//    public void exec() throws IOException {
//        String firstLine = input.readLine();
//        String[] strings = firstLine.split(" ");
//        int start = Integer.parseInt(strings[0]);
//        int end = Integer.parseInt(strings[1]);
//        int numberOfImages = Integer.parseInt(strings[2]);
//
//        List<Image> images = new ArrayList<Image>();
//
//        for (int i = 0; i < numberOfImages; i++) {
//
//            images.add( new Image(input));
//        }
//
//        List<Integer> images_sorted = images.stream().sorted((o1, o2) ->
//                {
//                    return o1.timestamp - o2.timestamp;
//                }
//        ).filter(o -> o.hasAsteroid).map(o -> o.timestamp).collect(Collectors.toList());
//
//        for (int i : images_sorted){
//
//            output.writeLine(""+i);
//        }
//        System.out.println(images_sorted);
//    }
//
//}
//
