/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import at.perses.io.FileInput;
import at.perses.io.FileOutput;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;

public class Level1Test {
    private static final Logger logger = LogManager.getLogger(Level1Test.class.getName());

    private String inPath = "resources/Level1.in";
    private String outPath = "resources/Level1.out";

    private FileInput input;
    private FileOutput output;

    @Before
    public void setUp() throws IOException {
        input = new FileInput(inPath);
        output = new FileOutput(outPath);
        logger.info("Setup done");
    }

    @After
    public void tearDown() throws IOException {
        logger.info("Tear down...");
        output.close();
        input.close();
    }

    @Test
    public void exec() throws IOException {
        output.write("hallloooooo.... :P : ");
        output.writeLine("jakob");

        for (; ; ) {
            String line = input.readLine();
            if (line == null) {
                break;
            }

            logger.debug(line);
        }
    }

}

