/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import at.perses.contest.Image;
import at.perses.contest.Match;
import at.perses.io.FileInput;
import at.perses.io.FileOutput;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.awt.image.AreaAveragingScaleFilter;
import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

public class Level2Test {
    private static final Logger logger = LogManager.getLogger(Level2Test.class.getName());

    private String inPath =  "resources/level2/lvl2-4.inp";
    private String outPath = "resources/level2/lvl2-4.out";

    private FileInput input;
    private FileOutput output;

    @Before
    public void setUp() throws IOException {
        input = new FileInput(inPath);
        output = new FileOutput(outPath);
        logger.info("Setup done");
    }

    @After
    public void tearDown() throws IOException {
        logger.info("Tear down...");
        output.close();
        input.close();
    }


    @Test
    public void exec() throws IOException {
        String firstLine = input.readLine();
        String[] strings = firstLine.split(" ");
        int start = Integer.parseInt(strings[0]);
        int end = Integer.parseInt(strings[1]);
        int numberOfImages = Integer.parseInt(strings[2]);

        List<Image> images = new ArrayList<Image>();

        for (int i = 0; i < numberOfImages; i++) {

            images.add(new Image(input).clip());
        }

        //noinspection Duplicates


        images = images.stream().sorted(Comparator.comparingInt(o2 -> o2.timestamp)
        ).filter(o -> o.hasAsteroid()).collect(Collectors.toList());

        List<Match> matches = new ArrayList<>();
        List<Integer> consumedImages = new ArrayList<>();

        for (Image image : images) {
            if (consumedImages.contains(image.timestamp)){
                continue;
            }

            Match match = new Match(image);


            for(Image other :images){
                if (other == image){
                    continue;
                }
                if(image.compareMono(other)){
                    match.matchCount++;
                    match.lastOccurence = other.timestamp;
                    consumedImages.add(other.timestamp);

                }
            }
            matches.add(match);
        }

        for (Match match : matches){
            output.writeLine(""+match.firstOccurence + " " + match.lastOccurence + " " +match.matchCount);
        }
    }

}

